spring:
  profiles:
    active: dev
  application:
    name: zenTalk-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://${zenTalk.mysql.host}:${zenTalk.mysql.port}/${zenTalk.mysql.database}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${zenTalk.mysql.username}
    password: ${zenTalk.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${zenTalk.redis.host}
    port: ${zenTalk.redis.port}
    database: ${zenTalk.redis.database}
    timeout: 10000
  jackson:
    serialization:
      write_dates_as_timestamps: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
server:
  port: ${zenTalk.server.port}
  servlet:
    context-path: /api
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
knife4j:
  enable: true
  setting:
    language: zh_cn
wx:
  mp:
    callback: ${zenTalk.wx.callback}
    configs:
      - appId: ${zenTalk.wx.appId} # 第一个公众号的appid
        secret: ${zenTalk.wx.appSecret} # 公众号的appsecret
        token: ${zenTalk.wx.token} # 接口配置里的Token值
        aesKey: ${zenTalk.wx.aesKey} # 接口配置里的EncodingAESKey值
zenTalk:
  jwt:
    secret: ${zenTalk.jwt.secret}